### ISSUE TITLE
nRF52840-DK with ATWINC1500 on SES

### ISSUE THREAD

**Issue by Ad1tya0** [khoih-prog/WiFiNINA_Generic#19]
OS: Ubuntu 20.04 LTS
Linux ad1tya0 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Context:

I'm trying to develop a project where I use a nRF52840 devkit and an ATWINC1500 WiFi module to give it WiFi connectivity. I want to use the WiFiNINA library for the interface, however I'm using Segger Embedded Studio for development and most of the examples I can find here about the board uses Adafruit libraries/Arduino IDE.
Could I get a pointer in the right direction as to where to go with it?

**Comment by khoih-prog** [comment]
I'm sorry I can't help anything here. 

I suggest that you post and ask for help on [**Adafruit Support Forum**](https://forums.adafruit.com)

As this is not an issue of the library, I'm closing now.

Good Luck,
