### ISSUE TITLE
Flush method not implemented

### ISSUE THREAD

**Issue by NachtRaveVL** [khoih-prog/WiFiNINA_Generic#22]
Get a linker issue here on some platforms. Should just be a simple {} addition.

https://github.com/khoih-prog/WiFiNINA_Generic/blob/a239f8e4269b3252873131e23bea31684f0e93bf/src/WiFiStorage_Generic.h#L215

**Comment by khoih-prog** [comment]
Hi @NachtRaveVL 

The new [**WiFiNINA_Generic releases v1.8.14-6**](https://github.com/khoih-prog/WiFiNINA_Generic/releases/tag/v1.8.14-6) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/WiFiNINA_Generic#contributions-and-thanks)

Best Regards,

---

### Releases v1.8.14-6

1. Add support to `Teensy 4.x` using `Adafruit Airlift Featherwing Co-Processor`
2. Fix `WiFiStorageFile.flush()` linker error in some platform. Check [Flush method not implemented #22](https://github.com/khoih-prog/WiFiNINA_Generic/issues/22)
3. Update `Packages' Patches`

Regards,
